# Generated by Django 4.1 on 2022-08-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('class_student', models.CharField(max_length=20)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
        ),
    ]
